baseURL = "https://JZhao1122.github.io/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "我的博客"
theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    style = "github"
    noClasses = false

[params]
  defaultTheme = "light"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true

[[menu.main]]
  identifier = "home"
  name = "首页"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "archives"
  name = "归档"
  url = "/archives/"
  weight = 20

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 30
